version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:11-jdk-stretch
    steps:
      - checkout
      - run: |
          apt-get update |
          apt-get install libpng-dev -y --no-install-recommends |
          apt-get install pkg-config |
          apt-get install autoconf libtool pkg-config nasm build-essential |
          apt-get update && apt-get install -y gcc make libpng-dev
      - setup_remote_docker
      - run: mvn clean install
      - run: docker login -u $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
      - run: mvn docker:build docker:push